apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeselector-pod
  labels:
    app: nginx
spec:
  nodeSelector:
    disktype: ssd
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80