apiVersion: v1
kind: Pod
metadata:
  name: mypod-secret
spec:
  containers:
  - name: busybox
    image: k8s.gcr.io/busybox
    command: [ "/bin/sh", "-c", "sleep 3600" ]
    env:
    # 定義環境變量
    - name: USER_NAME 
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
    - name: USER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
    volumeMounts:
    - name: secret
      mountPath: "/config"
      readOnly: true
  volumes:
  # 可以在 Pod 級別設置卷，然後將其掛載到 Pod 内的容器中
  - name: secret
    secret:
      # 提供你想要掛載的 Secret 名字
      secretName: mysecret