apiVersion: v1 
kind: Pod 
metadata:
  name: nginx-nodeaffinity-pod
spec:
  affinity: 
    nodeAffinity:
      # 硬策略
      requiredDuringSchedulingIgnoredDuringExecution: 
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu 
            operator: In 
            values:
            - nvidia-tesla
      # 軟策略
      preferredDuringSchedulingIgnoredDuringExecution: 
      - weight: 1
        preference: 
          matchExpressions: 
          - key: group
            operator: In 
            values:
            - ai
  containers:
  - name: web
    image: nginx
 